export const USERS_JOB_NAMES = {
    RESET_MANY_USERS_TRAFFIC: 'resetManyUsersTraffic',
    REVOKE_MANY_USERS_SUBSCRIPTION: 'revokeManyUsersSubscription',
    UPDATE_MANY_USERS: 'updateManyUsers',
    EXPIRE_USER_NOTIFICATIONS: 'expireUserNotifications',
    DELETE_BY_STATUS: 'deleteByStatus',
    ADD_SUBSCRIPTION_REQUEST_RECORD: 'addSubscriptionRequestRecord',
    UPSERT_HWID_DEVICE: 'upsertHwidDevice',
    RESET_DAILY_USER_TRAFFIC: 'resetDailyUserTraffic',
    RESET_MONTHLY_USER_TRAFFIC: 'resetMonthlyUserTraffic',
    RESET_MONTHLY_ROLLING_USER_TRAFFIC: 'resetMonthlyRollingUserTraffic',
    RESET_NO_RESET_USER_TRAFFIC: 'resetNoResetUserTraffic',
    RESET_WEEKLY_USER_TRAFFIC: 'resetWeeklyUserTraffic',
    FIND_EXPIRED_USERS: 'findExpiredUsers',
    FIND_EXCEEDED_TRAFFIC_USAGE_USERS: 'findExceededTrafficUsageUsers',
    FIND_USERS_FOR_THRESHOLD_NOTIFICATION: 'findUsersForThresholdNotification',
    FIND_NOT_CONNECTED_USERS_NOTIFICATION: 'findNotConnectedUsersNotification',
    FIRE_USER_EVENT: 'fireUserEvent',
    UPDATE_USERS_USAGE: 'updateUsersUsage',
    BULK_UPDATE_ALL_USERS: 'bulkUpdateAllUsers',
    RESET_ALL_USER_TRAFFIC: 'resetAllUserTraffic',
    BULK_ALL_EXTEND_EXPIRATION_DATE: 'bulkAllExtendExpirationDate',
} as const;
