import { CronExpression } from '@nestjs/schedule';

const EVERY_15_SECONDS = '*/15 * * * * *';
const EVERY_45_SECONDS = '*/45 * * * * *';

const EVERY_DAY_AT_MIDNIGHT_AND_5_MINUTES = '5 0 * * *';
const EVERY_DAY_AT_MIDNIGHT_AND_10_MINUTES = '10 0 * * *';
const EVERY_WEEK_AT_MONDAY_MIDNIGHT_AND_15_MINUTES = '15 0 * * 1';
const EVERY_1ST_DAY_OF_MONTH_AT_MIDNIGHT_AT_20_MINUTES = '20 0 1 * *';

const EVERY_WEEK_AT_MONDAY_00_30 = '30 0 * * 1';
const EVERY_WEEK_AT_MONDAY_00_45 = '45 0 * * 1';

export const JOBS_INTERVALS = {
    METRIC_EXPORT_METRICS: EVERY_15_SECONDS,
    METRIC_SYNC_METRICS: CronExpression.EVERY_6_HOURS,

    NODE_HEALTH_CHECK: CronExpression.EVERY_10_SECONDS,
    RECORD_NODE_USAGE: CronExpression.EVERY_30_SECONDS,

    RESET_NODE_TRAFFIC: CronExpression.EVERY_DAY_AT_1AM,
    REVIEW_NODES: CronExpression.EVERY_HOUR,

    RECORD_USER_USAGE: EVERY_15_SECONDS,

    EXPORT_NODE_CONNECTIONS: CronExpression.EVERY_5_MINUTES,

    RESET_USER_TRAFFIC: {
        DAILY: EVERY_DAY_AT_MIDNIGHT_AND_5_MINUTES,
        MONTHLY_ROLLING: EVERY_DAY_AT_MIDNIGHT_AND_10_MINUTES,
        WEEKLY: EVERY_WEEK_AT_MONDAY_MIDNIGHT_AND_15_MINUTES,
        MONTHLY: EVERY_1ST_DAY_OF_MONTH_AT_MIDNIGHT_AT_20_MINUTES,
    },
    REVIEW_USERS: {
        FIND_EXCEEDED_TRAFFIC_USAGE_USERS: EVERY_45_SECONDS,
        FIND_EXPIRED_USERS: CronExpression.EVERY_30_SECONDS,
    },
    EXPIRE_NOTIFICATIONS: CronExpression.EVERY_MINUTE,

    BANDWIDTH_USAGE_NOTIFICATIONS: {
        FIND_USERS_TO_SEND_NOTIFICATIONS: CronExpression.EVERY_5_MINUTES,
    },
    NOT_CONNECTED_USERS_NOTIFICATIONS: {
        FIND_USERS_TO_SEND_NOTIFICATIONS: CronExpression.EVERY_10_MINUTES,
    },

    SERVICE: {
        CLEAN_OLD_USAGE_RECORDS: EVERY_WEEK_AT_MONDAY_00_30,
        VACUUM_TABLES: EVERY_WEEK_AT_MONDAY_00_45,
    },
    CRM: {
        INFRA_BILLING_NODES_NOTIFICATIONS: CronExpression.EVERY_DAY_AT_5PM,
    },
} as const;
